import { inject, provide } from "vue";

export const CHECKOUT_FLOW_KEY = Symbol("checkoutFlow");

export function provideCheckoutFlow(flow) {
    provide(CHECKOUT_FLOW_KEY, flow);
}

export function useCheckoutFlowContext() {
    const flow = inject(CHECKOUT_FLOW_KEY);
    if (!flow) {
        throw new Error(
            "useCheckoutFlowContext: ожидается provideCheckoutFlow() в CartDockPanel",
        );
    }

    const {
        cartStore,
        userStore,
        activeStep,
        isGuestCheckout,
        newAddressForm,
        newAddressLoading,
        newAddressError,
        isNewAddressOpen,
        guestStepError,
        deliveryStepError,
        paymentStepError,
        cartItems,
        userCartItems,
        systemCartItems,
        totalAmount,
        itemsTotalAmount,
        deliveryFeeAmount,
        isDeliveryFree,
        userTotalAmount,
        systemTotalAmount,
        promoState,
        formatPrice,
        formatPhone,
        isAuthenticated,
        hasCartItems,
        canResumeCheckout,
        resumeCheckoutLabel,
        checkoutIntent,
        orderStore,
        checkoutStepMeta,
        handleStartCheckout,
        handleContinueAsGuest,
        handleResumeCheckout,
        openProfileDock,
        goToCart,
        goToGuest,
        goToDelivery,
        goToGuestNext,
        goToPayment,
        goToConfirm,
        goToSuccess,
        setDeliveryMethod,
        setDeliveryComment,
        setGuestContact,
        patchDeliveryAddress,
        selectAddress,
        setPaymentMethod,
        setPaymentChangeFrom,
        setCustomerComment,
        handleConfirmOrder,
        handleCreateAddress,
        toggleNewAddressOpen,
    } = flow;

    const checkoutState = {
        checkoutIntent,
        orderStore,
        cartStore,
        cartItems,
        userCartItems,
        systemCartItems,
        totalAmount,
        itemsTotalAmount,
        deliveryFeeAmount,
        isDeliveryFree,
        userTotalAmount,
        systemTotalAmount,
        promoState,
        formatPrice,
        formatPhone,
        isAuthenticated,
        hasCartItems,
        canResumeCheckout,
        resumeCheckoutLabel,
        activeStep,
        isGuestCheckout,
        checkoutStepMeta,
        newAddressForm,
        newAddressLoading,
        newAddressError,
        isNewAddressOpen,
        guestStepError,
        deliveryStepError,
        paymentStepError,
    };

    return {
        cartStore,
        userStore,
        checkoutState,
        checkoutStepMeta,
        handleStartCheckout,
        handleContinueAsGuest,
        handleResumeCheckout,
        openProfileDock,
        goToCart,
        goToGuest,
        goToDelivery,
        goToGuestNext,
        goToPayment,
        goToConfirm,
        goToSuccess,
        setDeliveryMethod,
        setDeliveryComment,
        setGuestContact,
        patchDeliveryAddress,
        selectAddress,
        setPaymentMethod,
        setPaymentChangeFrom,
        setCustomerComment,
        handleConfirmOrder,
        handleCreateAddress,
        toggleNewAddressOpen,
    };
}
