import { inject, provide } from "vue";

export const CHECKOUT_FLOW_KEY = Symbol("checkoutFlow");

export function provideCheckoutFlow(flow) {
    provide(CHECKOUT_FLOW_KEY, flow);
}

export function useCheckoutFlowContext() {
    const flow = inject(CHECKOUT_FLOW_KEY);
    if (!flow) {
        throw new Error(
            "useCheckoutFlowContext: ожидается provideCheckoutFlow() в CartDockPanel",
        );
    }

    const {
        cartStore,
        userStore,
        activeStep,
        isGuestCheckout,
        newAddressForm,
        newAddressLoading,
        newAddressError,
        isNewAddressOpen,
        guestStepError,
        deliveryStepError,
        paymentStepError,
        cartItems,
        userCartItems,
        systemCartItems,
        totalAmount,
        itemsTotalAmount,
        deliveryFeeAmount,
        isDeliveryFree,
        hasDeliveryPricing,
        userTotalAmount,
        systemTotalAmount,
        promoState,
        benefitsProgress,
        deliveryBenefit,
        giftBenefit,
        benefits,
        formatPrice,
        formatPhone,
        isAuthenticated,
        hasCartItems,
        checkoutIntent,
        checkoutStore,
        orderStore,
        checkoutStepMeta,
        handleStartCheckout,
        handleContinueAsGuest,
        openProfileDock,
        goToCart,
        goToGuest,
        goToDelivery,
        goToGuestNext,
        goToPayment,
        goToConfirm,
        goToSuccess,
        setDeliveryMethod,
        setDeliveryComment,
        setGuestContact,
        patchDeliveryAddress,
        selectAddress,
        setPaymentMethod,
        setPaymentChangeFrom,
        setCustomerComment,
        handleConfirmOrder,
        confirmLoading,
        confirmError,
        lastCreatedOrder,
        handleCreateAddress,
        toggleNewAddressOpen,
        scheduleDeliveryPreview,
        flushDeliveryPreview,
    } = flow;

    const checkoutState = {
        checkoutIntent: checkoutIntent ?? checkoutStore,
        checkoutStore: checkoutStore ?? checkoutIntent,
        orderStore,
        cartStore,
        cartItems,
        userCartItems,
        systemCartItems,
        totalAmount,
        itemsTotalAmount,
        deliveryFeeAmount,
        isDeliveryFree,
        hasDeliveryPricing,
        userTotalAmount,
        systemTotalAmount,
        promoState,
        benefitsProgress,
        deliveryBenefit,
        giftBenefit,
        benefits,
        formatPrice,
        formatPhone,
        isAuthenticated,
        hasCartItems,
        activeStep,
        isGuestCheckout,
        checkoutStepMeta,
        newAddressForm,
        newAddressLoading,
        newAddressError,
        isNewAddressOpen,
        guestStepError,
        deliveryStepError,
        paymentStepError,
        confirmLoading,
        confirmError,
        lastCreatedOrder,
    };

    return {
        cartStore,
        userStore,
        checkoutState,
        checkoutStepMeta,
        handleStartCheckout,
        handleContinueAsGuest,
        openProfileDock,
        goToCart,
        goToGuest,
        goToDelivery,
        goToGuestNext,
        goToPayment,
        goToConfirm,
        goToSuccess,
        setDeliveryMethod,
        setDeliveryComment,
        setGuestContact,
        patchDeliveryAddress,
        selectAddress,
        setPaymentMethod,
        setPaymentChangeFrom,
        setCustomerComment,
        handleConfirmOrder,
        confirmLoading,
        confirmError,
        lastCreatedOrder,
        handleCreateAddress,
        toggleNewAddressOpen,
        scheduleDeliveryPreview,
        flushDeliveryPreview,
    };
}
